# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://leatrix@github.com/leatrix/leatrix-sounds-classic.git"
          source_branch: "main"
          destination_repo: "https://gitlab.com/leatrix/leatrix-sounds-classic.git"
          destination_branch: "main"
          token: ${{ secrets.GIBLAB_KEY }}
